language: python

python:
  - "3.7"

arch:
  - arm64

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

jobs:
  include:
    - stage: Firmware Tests
      name: Test Against Firmware 215
      script:
        - docker pull vinteo81/opensprinkler-firmware:215
        - docker run -d -p 127.0.0.1:8215:8080 vinteo81/opensprinkler-firmware:215
        - docker ps -a
        - sleep 2
        - curl 'http://localhost:8215/sp?pw=opendoor&npw=a6d82bced638de3def1e9bbb4983225c&cpw=a6d82bced638de3def1e9bbb4983225c'
        - CONTROLLER_URL=http://localhost:8215 CONTROLLER_FIRMWARE=215 pytest --cov=pyopensprinkler --cov-report=xml
    - stage: Firmware Tests
      name: Test Against Firmware 216
      script:
        - docker pull vinteo81/opensprinkler-firmware:216
        - docker run -d -p 127.0.0.1:8216:8080 vinteo81/opensprinkler-firmware:216
        - docker ps -a
        - sleep 2
        - curl 'http://localhost:8216/sp?pw=opendoor&npw=a6d82bced638de3def1e9bbb4983225c&cpw=a6d82bced638de3def1e9bbb4983225c'
        - CONTROLLER_URL=http://localhost:8216 CONTROLLER_FIRMWARE=216 pytest --cov=pyopensprinkler --cov-report=xml
    - stage: Firmware Tests
      name: Test Against Firmware 217
      script:
        - docker pull vinteo81/opensprinkler-firmware:217
        - docker run -d -p 127.0.0.1:8217:8080 vinteo81/opensprinkler-firmware:217
        - docker ps -a
        - sleep 2
        - CONTROLLER_URL=http://localhost:8217 CONTROLLER_FIRMWARE=217 pytest --cov=pyopensprinkler --cov-report=xml
    - stage: Firmware Tests
      name: Test Against Firmware 218
      script:
        - docker pull vinteo81/opensprinkler-firmware:218
        - docker run -d -p 127.0.0.1:8218:8080 vinteo81/opensprinkler-firmware:218
        - docker ps -a
        - sleep 2
        - curl 'http://localhost:8218/sp?pw=opendoor&npw=a6d82bced638de3def1e9bbb4983225c&cpw=a6d82bced638de3def1e9bbb4983225c'
        - CONTROLLER_URL=http://localhost:8218 CONTROLLER_FIRMWARE=218 pytest --cov=pyopensprinkler --cov-report=xml
    - stage: Firmware Tests
      name: Test Against Firmware 219
      script:
        - docker pull vinteo81/opensprinkler-firmware:219
        - docker run -d -p 127.0.0.1:8219:8080 vinteo81/opensprinkler-firmware:219
        - docker ps -a
        - sleep 2
        - curl 'http://localhost:8219/sp?pw=opendoor&npw=a6d82bced638de3def1e9bbb4983225c&cpw=a6d82bced638de3def1e9bbb4983225c'
        - CONTROLLER_URL=http://localhost:8219 CONTROLLER_FIRMWARE=219 pytest --cov=pyopensprinkler --cov-report=xml
    - stage: Firmware Tests
      name: Test Against Firmware 219 (4)
      script:
        - docker pull vinteo81/opensprinkler-firmware:219_4
        - docker run -d -p 127.0.0.1:4219:8080 vinteo81/opensprinkler-firmware:219_4
        - docker ps -a
        - sleep 2
        - curl 'http://localhost:4219/sp?pw=opendoor&npw=a6d82bced638de3def1e9bbb4983225c&cpw=a6d82bced638de3def1e9bbb4983225c'
        - CONTROLLER_URL=http://localhost:4219 CONTROLLER_FIRMWARE=219.4 pytest --cov=pyopensprinkler --cov-report=xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
